//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string ICNumber { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string HomeNumber { get; set; }
        public string HandPhoneNumber { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<decimal> PayRate { get; set; }
    }
}
