//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public string FoodID { get; set; }
        public string FoodName { get; set; }
        public string FoodDesc { get; set; }
        public string FoodType { get; set; }
        public Nullable<decimal> FoodPrice { get; set; }
        public string FoodStatus { get; set; }
    }
}
