//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CafeManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string MemberID { get; set; }
        public string Name { get; set; }
        public string ICNumber { get; set; }
        public string Address { get; set; }
        public string ContactHP { get; set; }
        public string ContactHome { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Status { get; set; }
        public Nullable<int> MemberPoint { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
